stop_words = [
    " ",
    "???",
    ". ltd.",
    ".htaccess redirect",
    ".ltd.",
    "",
    "*** n/a ***",
    "01-scripts",
    "12.x",
    "2.x",
    "3.17S",
    "3.18.0S",
    "3.18.0SP",
    "3.18.1S",
    "aam",
    "academy",
    "access management",
    "access manager.",
    "access manager",
    "access",
    "act",
    "actions",
    "activity",
    "addons",
    "address book plugin",
    "admin",
    "administration",
    "afm",
    "agca",
    "ai chatbot",
    "aim",
    "alex",
    "album",
    "all versions",
    "amazon",
    "amelia",
    "amen",
    "analysis",
    "and more",
    "and",
    "anker",
    "anti-spam",
    "anti-virus",
    "antilles",
    "antivirus",
    "apm",
    "apollo",
    "app",
    "application",
    "apps",
    "are",
    "armeria",
    "asm",
    "astra",
    "at&t",
    "atahualpa",
    "august",
    "austin",
    "automation",
    "backup",
    "barker",
    "basil",
    "baxter",
    "been",
    "basis",
    "budget",
    "blocks",
    "bridge",
    "before",
    "bhima",
    "bifrost",
    "billing",
    "binary",
    "bind",
    "bing",
    "bios",
    "bis",
    "bixby",
    "black",
    "blog",
    "bolt",
    "booth",
    "bot",
    "bottle",
    "brave",
    "breeze",
    "bridge",
    "browser",
    "browsers",
    "budget",
    "bug library",
    "build service",
    "build",
    "buildroot",
    "bulk add to cart for woocommerce",
    "bulk comment remove",
    "bulk creator",
    "bulk edit",
    "business edition",
    "butter",
    "button",
    "buttons",
    "buy me a coffee – button",
    "buy now button",
    "by",
    "cafe",
    "call me back",
    "call",
    "calliope",
    "calls",
    "campaign",
    "capture",
    "canon",
    "carousel",
    "carrot",
    "cash",
    "catalog mode",
    "categories",
    "category",
    "cati",
    "caty",
    "cdn",
    "center",
    "central licensing system",
    "centre",
    "chalk",
    "challenge",
    "challenge",
    "change control",
    "change memory limit",
    "change table prefix",
    "change upload file permissions",
    "chat",
    "chatbot",
    "chicken",
    "class",
    "clerk",
    "client",
    "clone",
    "cloud agent",
    "cloud",
    "cmc",
    "cms",
    "co-authors",
    "code snippets",
    "collector software",
    "collector",
    "college",
    "colors",
    "comm",
    "comment license",
    "comment",
    "comments",
    "commerce",
    "common event enabler",
    "common licensing",
    "common",
    "communications billing",
    "communities",
    "community edition",
    "company",
    "compute",
    "configuration",
    "configure smtp",
    "configure",
    "confirm data",
    "connect",
    "containers",
    "content security policy",
    "content server",
    "content staging",
    "content transfer",
    "content",
    "control center",
    "control desk",
    "control",
    "cookies",
    "core",
    "corel",
    "cosmos",
    "cosy",
    "countdown block",
    "countdown timer",
    "countdown",
    "countup",
    "cpt",
    "crm",
    "crow",
    "crowd",
    "cta",
    "ctms",
    "culture",
    "cumin",
    "cups",
    "curveball",
    "custom add user",
    "custom banners",
    "custom css",
    "custom dashboard",
    "custom login page",
    "custom login redirect",
    "custom login",
    "custom post type",
    "customer",
    "customers online",
    "customers",
    "customization service",
    "customize button",
    "dalli",
    "darcie",
    "dart",
    "das",
    "dashboard",
    "data center",
    "data domain",
    "data loss prevention",
    "data masking",
    "data risk manager",
    "data security firewall",
    "data server",
    "data transfer",
    "date remover",
    "date",
    "debug",
    "delete me",
    "deliver",
    "denis",
    "design",
    "designer",
    "desktop client",
    "desktop",
    "desktops",
    "dev blog",
    "devops deploy",
    "dice",
    "dimension",
    "directory",
    "discourse",
    "discover",
    "discovery",
    "dns server",
    "dns",
    "doko",
    "domino",
    "download manager",
    "download media",
    "download monitor",
    "download plugin",
    "download station",
    "download theme",
    "download",
    "downloads",
    "dpa",
    "drag",
    "drivers for windows",
    "drop",
    "dropdown menu widget",
    "dropdown",
    "druid",
    "dsgvo",
    "dubbo",
    "duck",
    "duplicity",
    "domino",
    "dvr",
    "dxp",
    "e10",
    "e11",
    "e80",
    "earnings",
    "easy",
    "edd",
    "edge",
    "education",
    "effect",
    "efficient",
    "electra",
    "email",
    "embed pdf",
    "embed privacy",
    "embed swagger",
    "embed",
    "empire",
    "employee management system",
    "employee",
    "encrpytion",
    "engine",
    "engineering",
    "engines",
    "enlighten",
    "enterprise comm",
    "enterprise search",
    "entity embed",
    "envoy",
    "error log",
    "ess",
    "eva",
    "everything",
    "exam",
    "excel files",
    "export",
    "exports",
    "extend",
    "extension",
    "extensions",
    "external media",
    "external videos",
    "external",
    "factor",
    "falcon",
    "faq",
    "faster",
    "faye",
    "fedora",
    "fern",
    "field service",
    "field",
    "fields",
    "file manager",
    "file permissions",
    "file",
    "files",
    "find",
    "flow",
    "fluent",
    "focus",
    "football",
    "for",
    "foreman",
    "form",
    "forms",
    "fpc",
    "fps",
    "fraction",
    "framework",
    "frappe",
    "friends",
    "free",
    "from",
    "fuchsia",
    "fuer",
    "für",
    "gallagher",
    "galleria",
    "garden",
    "gateway",
    "genie",
    "geon",
    "gerrit",
    "gipsy",
    "glass",
    "global",
    "gmbh",
    "gold",
    "gotham",
    "goto",
    "goya",
    "granth",
    "grs",
    "gutenberg",
    "guardian",
    "haas",
    "had",
    "hal",
    "halcyon",
    "hard",
    "has",
    "haskel",
    "have",
    "hawk",
    "helm",
    "helpful",
    "hermes",
    "highlight",
    "himalayas",
    "history",
    "hmi",
    "hot r",
    "hotdog",
    "hotel listing",
    "house rental",
    "http auth",
    "http server",
    "http-daemon",
    "http",
    "hyper",
    "identity",
    "image",
    "images",
    "immer",
    "import all pages",
    "import",
    "inc.",
    "inc",
    "include",
    "infrastructure",
    "intelligence",
    "insight",
    "inventor",
    "inventory agent",
    "inventory management system",
    "inventory manager",
    "inventory",
    "inverter",
    "invoice",
    "invoices",
    "ip camera",
    "ips",
    "jami",
    "java",
    "jenkins",
    "joplin",
    "jupiter",
    "kata",
    "kavita",
    "kies",
    "kit",
    "knowledge",
    "kura",
    "labor",
    "landscape",
    "lawyer",
    "line",
    "linker",
    "live",
    "location",
    "log",
    "login",
    "longhorn",
    "lost",
    "ltd.",
    "ltd",
    "lynx",
    "mac",
    "mail",
    "mall",
    "management",
    "manager",
    "marked",
    "maya",
    "mazda",
    "medium",
    "medusa",
    "meridian",
    "meris",
    "messages",
    "meta",
    "micro",
    "migrate",
    "min",
    "minerva",
    "mini",
    "mit",
    "mobile",
    "mom",
    "moment",
    "monitor",
    "monkey",
    "mono",
    "more",
    "mosaic",
    "msp",
    "mule",
    "multiple",
    "n/",
    "n/a",
    "nessus",
    "netty",
    "newsletter",
    "niagara",
    "notebook",
    "notes",
    "notice",
    "not a product",
    "noxen",
    "oceanic",
    "october",
    "odyssey",
    "omaha",
    "one",
    "online",
    "operations",
    "options",
    "order",
    "orders",
    "orion",
    "otter",
    "page",
    "pages",
    "panel",
    "panorama",
    "path",
    "pay",
    "pdf editor",
    "pdf invoices",
    "pdf",
    "pds",
    "pem",
    "performance",
    "phone",
    "phones",
    "pillow",
    "pipeline",
    "pipeline",
    "plate",
    "platform",
    "plato",
    "play",
    "playlist",
    "pluto",
    "points",
    "poll",
    "portal",
    "porto",
    "pos",
    "post",
    "posts",
    "powerful",
    "premium",
    "premiere",
    "prime",
    "printer",
    "product",
    "products",
    "project",
    "proto",
    "proton",
    "public",
    "pulse",
    "qemu:",
    "quiz",
    "quotes",
    "rdp",
    "reader",
    "recently",
    "red",
    "register",
    "reminder",
    "remote access",
    "remote administration console",
    "remote client",
    "remote",
    "replace all",
    "replace",
    "report",
    "reports",
    "reporting",
    "reports",
    "requests",
    "resilient",
    "response",
    "reward",
    "rewards",
    "routine",
    "rider",
    "roots",
    "rsvp",
    "runtime",
    "safe",
    "sal",
    "salt",
    "saul",
    "scripting",
    "secure",
    "security",
    "see",
    "serve",
    "server",
    "services system",
    "services",
    "ses",
    "session",
    "share",
    "sharing",
    "sharp",
    "shell",
    "silesia",
    "simple",
    "sinatra",
    "sms",
    "smtp",
    "soledad",
    "spa",
    "spring",
    "sso",
    "standard",
    "stockholm",
    "styles",
    "sumo",
    "sunshine",
    "survey",
    "sync",
    "tab",
    "tags",
    "tasks",
    "team",
    "teams",
    "testing",
    "text",
    "that",
    "the",
    "these",
    "this",
    "those",
    "three",
    "ticker",
    "ticket",
    "tickets",
    "time",
    "times",
    "tips",
    "titles",
    "top 10",
    "top 25 social icons",
    "top bar",
    "total",
    "tower",
    "triton",
    "twig",
    "types",
    "typha",
    "u-boot",
    "und",
    "unix",
    "unknown",
    "unspecified",
    "upc",
    "upcoming event",
    "update server",
    "update",
    "upload form",
    "upload resume",
    "uploader",
    "url shortener",
    "usb copy",
    "users",
    "usg",
    "usoc",
    "utilities",
    "vault",
    "version",
    "versions",
    "video",
    "view",
    "voice",
    "vpn",
    "wagtail",
    "was",
    "web",
    "website",
    "were",
    "when",
    "where",
    "which",
    "who",
    "whom",
    "whose",
    "why",
    "winter",
    "with",
    "word",
    "worthy",
    "yard",
    "yuki",
    "zeit",
    "zephyr",
]
