stop_words = [
    " ",
    "",
    "???",
    "12.x",
    "2.x",
    "3.17S",
    "3.18.0S",
    "3.18.0SP",
    "3.18.1S",
    "anker",
    "anti-virus",
    "anti-spam",
    "antivirus",
    "apollo",
    "automation",
    "academy",
    "access",
    "access manager",
    "access management",
    "access manager.",
    "act",
    "actions",
    "activity",
    "aim",
    "ai chatbot",
    "amelia",
    "alex",
    "all versions",
    "and",
    "and more",
    "app",
    "application",
    "administration",
    "are",
    "august",
    "barker",
    "baxter",
    "backup",
    "buttons",
    "buy now button",
    "black",
    "been",
    "button",
    "binary",
    "*** n/a ***",
    ". ltd.",
    ".ltd.",
    ".htaccess redirect",
    "01-scripts",
    "bis",
    "billing",
    "blog",
    "bolt",
    "bot",
    "bottle",
    "brave",
    "browser",
    "before",
    "browsers",
    "bulk add to cart for woocommerce",
    "bulk comment remove",
    "bulk creator",
    "bulk edit",
    "business edition",
    "bug library",
    "build service",
    "build",
    "buildroot",
    "butter",
    "buy me a coffee – button",
    "by",
    "call",
    "calls",
    "caty",
    "call me back",
    "categories",
    "category",
    "carousel",
    "carrot",
    "catalog mode",
    "canon",
    "cash",
    "cdn",
    "center",
    "central licensing system",
    "centre",
    "chalk",
    "change control",
    "change memory limit",
    "change table prefix",
    "change upload file permissions",
    "challenge",
    "chicken",
    "chat",
    "chatbot",
    "client",
    "clone",
    "cloud",
    "cloud agent",
    "clerk",
    "corel",
    "colors",
    "collector",
    "collector software",
    "comment",
    "common licensing",
    "common event enabler",
    "communications billing",
    "community edition",
    "configure",
    "configure smtp",
    "confirm data",
    "content server",
    "content security policy",
    "content staging",
    "content transfer",
    "control center",
    "control desk",
    "college",
    "cosy",
    "countdown",
    "countdown timer",
    "countdown block",
    "countup",
    "crow",
    "crowd",
    "co-authors",
    "code snippets",
    "common",
    "company",
    "culture",
    "challenge",
    "communities",
    "comments",
    "comment license",
    "comm",
    "crm",
    "connect",
    "configuration",
    "containers",
    "content",
    "control",
    "core",
    "cosmos",
    "cumin",
    "cups",
    "curveball",
    "customize button",
    "customization service",
    "customers online",
    "customers",
    "custom css",
    "custom banners",
    "custom add user",
    "custom dashboard",
    "custom login",
    "custom login page",
    "custom login redirect",
    "custom post type",
    "customer",
    "das",
    "date",
    "dart",
    "data center",
    "data domain",
    "data loss prevention",
    "data risk manager",
    "data security firewall",
    "data server",
    "data transfer",
    "date remover",
    "data masking",
    "dashboard",
    "dev blog",
    "debug",
    "desktop",
    "delete me",
    "design",
    "denis",
    "desktops",
    "desktop client",
    "devops deploy",
    "discourse",
    "discover",
    "discovery",
    "dimension",
    "download",
    "download manager",
    "download media",
    "download plugin",
    "download station",
    "download theme",
    "downloads",
    "download monitor",
    "drop",
    "drag",
    "drivers for windows",
    "dropdown",
    "dropdown menu widget",
    "dsgvo",
    "dns",
    "dns server",
    "duck",
    "duplicity",
    "dpa",
    "dvr",
    "dxp",
    "e10",
    "e11",
    "e80",
    "easy",
    "earnings",
    "ess",
    "education",
    "effect",
    "efficient",
    "electra",
    "email",
    "embed",
    "embed pdf",
    "embed swagger",
    "embed privacy",
    "employee",
    "employee management system",
    "engineering",
    "engines",
    "enlighten",
    "error log",
    "encrpytion",
    "enterprise comm",
    "enterprise search",
    "entity embed",
    "envoy",
    "engine",
    "extend",
    "exam",
    "external",
    "extension",
    "export",
    "exports",
    "excel files",
    "external media",
    "external videos",
    "faq",
    "faster",
    "field",
    "field service",
    "fields",
    "fern",
    "file",
    "file manager",
    "file permissions",
    "files",
    "find",
    "flow",
    "fluent",
    "focus",
    "for",
    "form",
    "forms",
    "fraction",
    "frappe",
    "framework",
    "football",
    "free",
    "from",
    "fuer",
    "für",
    "garden",
    "gateway",
    "gallagher",
    "granth",
    "gmbh",
    "gold",
    "goto",
    "had",
    "hard",
    "has",
    "haas",
    "have",
    "helpful",
    "http",
    "http auth",
    "http server",
    "http-daemon",
    "highlight",
    "hotdog",
    "hot r",
    "hotel listing",
    "house rental",
    "identitiy",
    "ip camera",
    "image",
    "images",
    "import",
    "import all pages",
    "immer",
    "inventor",
    "inventory",
    "inventory management system",
    "inventory agent",
    "inventory manager",
    "inverter",
    "invoice",
    "invoices",
    "inc",
    "inc.",
    "ips",
    "include",
    "infrastructure",
    "kit",
    "kies",
    "knowledge",
    "landscape",
    "line",
    "live",
    "labor",
    "lawyer",
    "login",
    "log",
    "ltd",
    "ltd.",
    "management",
    "manager",
    "mail",
    "medium",
    "messages",
    "migrate",
    "mit",
    "meta",
    "mini",
    "mobile",
    "mom",
    "moment",
    "monkey",
    "more",
    "mono",
    "mule",
    "multiple",
    "n/",
    "n/a",
    "notebook",
    "october",
    "one",
    "online",
    "order",
    "operations",
    "panel",
    "panorama",
    "path",
    "pay",
    "pipeline",
    "project",
    "posts",
    "prime",
    "plate",
    "pdf",
    "pdf invoices",
    "pdf editor",
    "garden",
    "hyper",
    "marked",
    "pipeline",
    "tasks",
    "platform",
    "post",
    "premium",
    "pulse",
    "proto",
    "printer",
    "product",
    "products",
    "public",
    "response",
    "recently",
    "remote",
    "red",
    "resilient",
    "requests",
    "remote access",
    "reminder",
    "remote administration console",
    "remote client",
    "replace",
    "replace all",
    "runtime",
    "roots",
    "safe",
    "scripting",
    "secure",
    "security",
    "see",
    "serve",
    "server",
    "session",
    "services",
    "services system",
    "simple",
    "share",
    "sharp",
    "shell",
    "standard",
    "survey",
    "tags",
    "tasks",
    "team",
    "text",
    "that",
    "the",
    "these",
    "this",
    "tips",
    "those",
    "three",
    "time",
    "times",
    "tower",
    "top 10",
    "top bar",
    "top 25 social icons",
    "titles",
    "ticker",
    "testing",
    "teams",
    "types",
    "twig",
    "und",
    "unknown",
    "unspecified",
    "users",
    "utilities",
    "update",
    "update server",
    "upcoming event",
    "uploader",
    "upload resume",
    "upload form",
    "usb copy",
    "unix",
    "url shortener",
    "u-boot",
    "version",
    "versions",
    "video",
    "voice",
    "vault",
    "vpn",
    "view",
    "was",
    "web",
    "website",
    "were",
    "when",
    "where",
    "which",
    "who",
    "whom",
    "whose",
    "why",
    "winter",
    "with",
    "qemu:",
    "yard",
    "zeit",
]
